#!/usr/bin/env bash
# Create a stable self-signed code-signing identity for development builds.
#
# Ad-hoc signed builds ("-") get a new identity on every build, and the
# login Keychain ties each stored secret (the Gmail sign-in) to the exact
# binary that wrote it, so every rebuild lost access to the account. A
# self-signed "OpenAGC Dev" certificate keeps the identity constant across
# builds. It lives only in your login Keychain and is trusted only for code
# signing; it does not let the app pass Gatekeeper on other Macs.
#
# Usage: scripts/dev-signing.sh          # creates the identity if missing
#        scripts/dev-signing.sh --remove # deletes it again
#
# Afterwards scripts/test-macos.sh signs Debug builds with it automatically
# (via macos/Local.xcconfig, gitignored). macOS may ask once to allow
# codesign to use the key: choose "Always Allow".
set -euo pipefail

NAME="OpenAGC Dev"
KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
XCCONFIG="$ROOT/macos/Local.xcconfig"

has_identity() {
  security find-identity -v -p codesigning "$KEYCHAIN" 2>/dev/null | grep -q "\"$NAME\""
}

if [[ "${1:-}" == "--remove" ]]; then
  security delete-identity -c "$NAME" "$KEYCHAIN" 2>/dev/null || true
  rm -f "$XCCONFIG"
  echo "dev-signing: removed \"$NAME\""
  exit 0
fi

if has_identity; then
  echo "dev-signing: \"$NAME\" already present"
else
  OPENSSL=/opt/homebrew/opt/openssl@3/bin/openssl
  [[ -x "$OPENSSL" ]] || OPENSSL=openssl
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  "$OPENSSL" req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout "$TMP/key.pem" -out "$TMP/cert.pem" -subj "/CN=$NAME" \
    -addext "keyUsage=critical,digitalSignature" \
    -addext "extendedKeyUsage=critical,codeSigning" \
    -addext "basicConstraints=critical,CA:false" 2>/dev/null
  # A throwaway password: the .p12 exists only for this import.
  # macOS's importer only reads the older PKCS#12 ciphers.
  "$OPENSSL" pkcs12 -export -inkey "$TMP/key.pem" -in "$TMP/cert.pem" \
    -out "$TMP/dev.p12" -passout pass:openagc -name "$NAME" \
    -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -macalg sha1
  security import "$TMP/dev.p12" -k "$KEYCHAIN" -P openagc \
    -T /usr/bin/codesign -T /usr/bin/security >/dev/null
  # Trust it for code signing in your user trust settings only. macOS may
  # ask for your login password here.
  security add-trusted-cert -r trustRoot -p codeSign -k "$KEYCHAIN" "$TMP/cert.pem"
  has_identity || { echo "dev-signing: identity not usable after import" >&2; exit 1; }
  echo "dev-signing: created \"$NAME\" in your login Keychain"
fi

cat > "$XCCONFIG" <<EOF
// Generated by scripts/dev-signing.sh (gitignored). Debug builds sign with
// a stable identity so the Keychain keeps trusting them across rebuilds.
CODE_SIGN_IDENTITY = $NAME
// No Team ID on a self-signed identity, so library validation must be off.
OPENAGC_ENTITLEMENTS = OpenAGC/Resources/OpenAGC-dev.entitlements
EOF
echo "dev-signing: wrote $XCCONFIG"
